# name: broaddus-isbi-csc-2021
# name: envs
dependencies:
  - python=3.6
  - ipython
  - tifffile
  - numpy
  - tqdm
  - scipy
  - scikit-image
  - pytorch
  - cudatoolkit=9.2
  - pip
  - pip:
    - pykdtree
